### PR TITLE
Camera setup

### PR DESCRIPTION
**Pull request by dlowrey**
- Removed support for RPi Camera devices
- Added face detection
- Added face tracking after detection
- Created `main.py` script to run the application and left space in it for a call to recognition methods (developed later)

Note: Some lines in `main.py` display the post-processed image on a screen. These will need to be removed after the application is tested.

### CODE REVIEW

**Comment by dlowrey** [comment]
I thought I had `master` branch latest changes, but the TravisCI builds are failing with some `yarn` stuff, do I need to merge a different branch?

**Comment by NilsG-S** [comment]
@dlowrey For some reason, the merge commit from @joyellealina's branch caused the tests to start failing. I've identified a solution to the problem, but it shouldn't have been effected by her changes. Unfortunately, the fix won't be up until I merge my branch.

**Comment by NilsG-S** [comment]
This is odd. I reverted to a previous commit `e68cb25`, ran `yarn install`, moved back to HEAD, ran `yarn install` again, and then the tests started working.

**Review by NilsG-S — APPROVED** [review]
Looks good

**Pull request merged**
